version: '3.8'

services:
  db:
    image: mysql:8.0
    restart: unless-stopped
    environment:
      MYSQL_DATABASE: riman_wp
      MYSQL_USER: riman_user
      MYSQL_PASSWORD: riman_pass_2024
      MYSQL_ROOT_PASSWORD: riman_root_2024
    volumes:
      - db_data:/var/lib/mysql
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost"]
      interval: 10s
      timeout: 5s
      retries: 5

  wordpress:
    image: wordpress:6.7-php8.2-apache
    restart: unless-stopped
    depends_on:
      db:
        condition: service_healthy
    ports:
      - "127.0.0.1:8801:80"
    environment:
      WORDPRESS_DB_HOST: db:3306
      WORDPRESS_DB_USER: riman_user
      WORDPRESS_DB_PASSWORD: riman_pass_2024
      WORDPRESS_DB_NAME: riman_wp
      WORDPRESS_DEBUG: 1
      WORDPRESS_CONFIG_EXTRA: |
        define('WP_DEFAULT_THEME', 'twentytwentyfive');
        define('WP_MEMORY_LIMIT', '256M');
        define('WP_MAX_MEMORY_LIMIT', '512M');
    volumes:
      - wp_data:/var/www/html
      - ./wp-content:/var/www/html/wp-content

  phpmyadmin:
    image: phpmyadmin:latest
    restart: unless-stopped
    depends_on:
      - db
    ports:
      - "127.0.0.1:8802:80"
    environment:
      PMA_HOST: db
      PMA_USER: riman_user
      PMA_PASSWORD: riman_pass_2024

  wpcli:
    image: wordpress:cli
    depends_on:
      db:
        condition: service_healthy
    user: "33:33"
    environment:
      WORDPRESS_DB_HOST: db:3306
      WORDPRESS_DB_USER: riman_user
      WORDPRESS_DB_PASSWORD: riman_pass_2024
      WORDPRESS_DB_NAME: riman_wp
    volumes:
      - wp_data:/var/www/html
      - ./wp-content:/var/www/html/wp-content

volumes:
  db_data:
  wp_data:
