#!/bin/bash
# Manual test script for All-Inkl SSH

echo "==================================="
echo "All-Inkl SSH/SFTP Test Script"
echo "==================================="
echo ""
echo "Deine Zugangsdaten:"
echo "-------------------"
echo "Host: w0181e1b.kasserver.com"
echo "User: w0181e1b"
echo "Pass: P4cTbHgiK7PuAC52HJLt"
echo ""
echo "Teste diese Befehle manuell im Terminal:"
echo ""
echo "1. SSH-Verbindung (gib Passwort ein wenn gefragt):"
echo "   ssh w0181e1b@w0181e1b.kasserver.com"
echo ""
echo "2. SFTP-Verbindung:"
echo "   sftp w0181e1b@w0181e1b.kasserver.com"
echo ""
echo "3. Mit sshpass (automatisch):"
echo "   sshpass -p 'P4cTbHgiK7PuAC52HJLt' ssh w0181e1b@w0181e1b.kasserver.com"
echo ""
echo "4. WP-CLI direkt:"
echo "   ssh w0181e1b@w0181e1b.kasserver.com 'cd /www/htdocs/w0181e1b && php wp-cli.phar --info'"
echo ""
echo "==================================="
echo ""
echo "Falls die Verbindung funktioniert, sag mir:"
echo "- Welcher Befehl funktioniert hat"
echo "- Was für eine Shell du hast (bash, sh, rssh, etc.)"
echo "- Ob WP-CLI verfügbar ist"
echo ""