#!/bin/bash
# Setup SSH für All-Inkl

echo "🔐 All-Inkl SSH Setup"
echo "====================="
echo ""
echo "Es gibt 2 verschiedene Benutzer bei All-Inkl:"
echo ""
echo "1. FTP/KAS Benutzer: w0181e1b"
echo "   - Für FTP-Zugriff"
echo "   - Für KAS-Login"
echo ""
echo "2. SSH Benutzer: ssh-w0181e1b"
echo "   - Für SSH-Shell Zugriff"
echo "   - Möglicherweise anderes Passwort"
echo ""
echo "Teste die Verbindung manuell:"
echo ""
echo "ssh ssh-w0181e1b@w0181e1b.kasserver.com"
echo ""
echo "Falls das Passwort anders ist:"
echo "1. Logge dich im KAS ein: https://kas.all-inkl.com"
echo "2. Gehe zu: Tools → SSH-Zugang"
echo "3. Setze/Prüfe das SSH-Passwort"
echo ""
echo "Oder erstelle einen SSH-Key:"
echo ""
echo "1. Generiere Key:"
echo "   ssh-keygen -t ed25519 -f ~/.ssh/allinkl_ssh -C 'all-inkl-ssh'"
echo ""
echo "2. Kopiere Public Key:"
echo "   cat ~/.ssh/allinkl_ssh.pub"
echo ""
echo "3. Füge im KAS unter SSH-Zugang → SSH-Keys hinzu"
echo ""
echo "4. Teste mit:"
echo "   ssh -i ~/.ssh/allinkl_ssh ssh-w0181e1b@w0181e1b.kasserver.com"
echo ""