name: Deploy to All-Inkl

on:
  push:
    branches: [ main ]
    paths:
      - 'wp-content/**'
      - '.github/workflows/**'
  workflow_dispatch:

jobs:
  deploy:
    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v3
    
    - name: Deploy WordPress files
      env:
        SSH_USERNAME: ${{ secrets.SSH_USERNAME }}
        KAS_PASSWORD: ${{ secrets.KAS_PASSWORD }}
        KAS_HOST: ${{ secrets.KAS_HOST }}
      run: |
        # Install sshpass
        sudo apt-get update
        sudo apt-get install -y sshpass rsync
        
        # Define remote path
        REMOTE_PATH="/www/htdocs/w0181e1b/riman-wordpress-swarm.ecomwy.com"
        
        # Sync WordPress themes (exclude node_modules)
        if [ -d "wp-content/themes" ]; then
          echo "📦 Syncing themes..."
          sshpass -p "$KAS_PASSWORD" rsync -avz --delete \
            --exclude='node_modules/' \
            --exclude='.git/' \
            --exclude='*.log' \
            -e "ssh -o StrictHostKeyChecking=no" \
            wp-content/themes/ \
            ${SSH_USERNAME}@${KAS_HOST}:${REMOTE_PATH}/wp-content/themes/
        fi
        
        # Sync WordPress plugins (exclude development files)
        if [ -d "wp-content/plugins" ]; then
          echo "🔌 Syncing plugins..."
          sshpass -p "$KAS_PASSWORD" rsync -avz --delete \
            --exclude='node_modules/' \
            --exclude='.git/' \
            --exclude='*.log' \
            --exclude='tests/' \
            -e "ssh -o StrictHostKeyChecking=no" \
            wp-content/plugins/ \
            ${SSH_USERNAME}@${KAS_HOST}:${REMOTE_PATH}/wp-content/plugins/
        fi
        
        # Sync custom PHP files
        for file in wp-content/*.php; do
          if [ -f "$file" ]; then
            echo "📄 Uploading $(basename $file)..."
            sshpass -p "$KAS_PASSWORD" scp -o StrictHostKeyChecking=no \
              "$file" \
              ${SSH_USERNAME}@${KAS_HOST}:${REMOTE_PATH}/wp-content/
          fi
        done
        
        # Clear WordPress cache
        echo "🧹 Clearing cache..."
        sshpass -p "$KAS_PASSWORD" ssh -o StrictHostKeyChecking=no \
          ${SSH_USERNAME}@${KAS_HOST} \
          "cd ${REMOTE_PATH} && wp cache flush 2>/dev/null || echo 'WP-CLI not available'"
        
        echo "✅ Deployment complete!"